name: Check for Existing Run

on:
  workflow_call:
    outputs:
      should_run:
        description: "Whether a CI run for this commit should proceed."
        value: ${{ jobs.check.outputs.should_run }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_run_status.outputs.result }}
    steps:
      - name: Check for existing successful CI run
        id: check_run_status
        uses: actions/github-script@v6
        with:
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml', // Replace with the name or ID of your main CI workflow file
              event: 'push', // Only check for 'push' runs to avoid circular logic
              head_sha: context.sha,
              status: 'success'
            });
            
            if (runs.workflow_runs.length > 0) {
              console.log('A successful CI run for this commit already exists. Skipping...');
              return 'false';
            }
            console.log('No successful CI run found. Proceeding...');
            return 'true';
